CREATE OR REPLACE PACKAGE ICIM.ICIM_UTILITIES
AS
    FUNCTION NONPRINTABLE_CHAR (TEST_STR_IN VARCHAR2)
        RETURN VARCHAR2;

     FUNCTION NONPRINTABLE_STRIP (SOURCE_STR_IN VARCHAR2)
        RETURN VARCHAR2;
END ICIM_UTILITIES;
/